/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.GoodRestHotel.view;

/**
 *
 * @author ggpin
 */
public class TelaCadQuartos extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadQuartos
     */
    public TelaCadQuartos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollQuartos = new javax.swing.JScrollPane();
        jpFundoQuartos = new javax.swing.JPanel();
        jpConsultaQuartos = new javax.swing.JPanel();
        lblBuscarQuartos = new javax.swing.JLabel();
        txtBuscarQuarto = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnLimparBusca = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setTitle("Good Rest Hotel - Cadastro Quartos");

        jScrollQuartos.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jpConsultaQuartos.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar"));

        lblBuscarQuartos.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblBuscarQuartos.setForeground(new java.awt.Color(0, 0, 0));
        lblBuscarQuartos.setText("Buscar quartos:");

        btnPesquisar.setText("Pesquisar");

        btnLimparBusca.setText("Limpar Busca");

        javax.swing.GroupLayout jpConsultaQuartosLayout = new javax.swing.GroupLayout(jpConsultaQuartos);
        jpConsultaQuartos.setLayout(jpConsultaQuartosLayout);
        jpConsultaQuartosLayout.setHorizontalGroup(
            jpConsultaQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultaQuartosLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lblBuscarQuartos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimparBusca)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jpConsultaQuartosLayout.setVerticalGroup(
            jpConsultaQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultaQuartosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpConsultaQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscarQuartos)
                    .addComponent(btnPesquisar)
                    .addComponent(btnLimparBusca))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpFundoQuartosLayout = new javax.swing.GroupLayout(jpFundoQuartos);
        jpFundoQuartos.setLayout(jpFundoQuartosLayout);
        jpFundoQuartosLayout.setHorizontalGroup(
            jpFundoQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFundoQuartosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpConsultaQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jpFundoQuartosLayout.setVerticalGroup(
            jpFundoQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFundoQuartosLayout.createSequentialGroup()
                .addComponent(jpConsultaQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 311, Short.MAX_VALUE))
        );

        jScrollQuartos.setViewportView(jpFundoQuartos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollQuartos, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollQuartos, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimparBusca;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JScrollPane jScrollQuartos;
    private javax.swing.JPanel jpConsultaQuartos;
    private javax.swing.JPanel jpFundoQuartos;
    private javax.swing.JLabel lblBuscarQuartos;
    private javax.swing.JTextField txtBuscarQuarto;
    // End of variables declaration//GEN-END:variables
}
